ServicoOrdenacaoFGV.MVC/ViewModels/Aggregation/OrderBooks.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ServicoOrdenacaoFGV.MVC.ViewModels.Aggregation
{
    public class OrderBooks
    {
        public List<Book> Books { get; set; }
        public List<Ordenation> Ordenations { get; set; }
    }
}

ServicoOrdenacaoFGV.MVC/ViewModels/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ServicoOrdenacaoFGV.MVC.ViewModels
{
    public partial class Book
    {
        public int BookId { get; set; }
        public string AuthorName { get; set; }
        public int EditionYear { get; set; }
        public string Title { get; set; }
    }
}

ServicoOrdenacaoFGV.MVC/ViewModels/Ordenation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ServicoOrdenacaoFGV.MVC.ViewModels
{
    public class Ordenation
    {
        public string Attribute { get; set; }
        public string Order { get; set; }
    }
}

ServicoOrdenacaoFGV.MVC/Controllers/BookController.cs
using ServicoOrdenacaoFGV.MVC.Utils;
using System.Configuration;
using System.Web.Mvc;
using Newtonsoft.Json;
using RestSharp;
using ServicoOrdenacaoFGV.MVC.ViewModels;
using ServicoOrdenacaoFGV.MVC.ViewModels.Aggregation;

namespace ServicoOrdenacaoFGV.MVC.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public object GetAll()
        {
            return JsonConvert.DeserializeObject(RestSharpUtils.OpenRequest(ConfigurationManager.AppSettings["ApiUrl"], "Book/GetBooks", Method.GET).Content);
        }

        [HttpPost]
        public object OrderBooks(OrderBooks orderBooks)
        {
            return JsonConvert.DeserializeObject(RestSharpUtils.OpenRequest(ConfigurationManager.AppSettings["ApiUrl"], "Book/OrderBooks", Method.POST, orderBooks).Content);
        }
    }
}

ServicoOrdenacaoFGV.MVC/Controllers/HomeController.cs
using RestSharp;
using ServicoOrdenacaoFGV.MVC.Utils;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ServicoOrdenacaoFGV.MVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

ServicoOrdenacaoFGV.MVC/Views/Book/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <section ng-app="BookApp">
        <div ng-controller="MainController as vm">
            <div class="scheudle-field">
                <fieldset class="livros">
                    <legend>Inserir Livros</legend>
                    <div class="InsertBooks">
                        <md-input-container class="md-block">
                            <label class="lblTitulo">Titulo</label>
                            <input required placeholder="Titulo do Livro" name="title" class="inputLivro" ng-model="vm.title">

                        </md-input-container>
                        <md-input-container class="md-block">
                            <label class="lblAutorNome">Autor</label>
                            <input placeholder="Autor do Livro" name="authorName" class="inputLivro" ng-model="vm.authorName">

                        </md-input-container>
                        <md-input-container class="md-block">
                            <label class="lblAnoEdicao">Ano</label>
                            <input type="number" placeholder="Ano da Edição" name="editionYear" class="inputLivro" ng-model="vm.editionYear">
                        </md-input-container>
                    </div>
                    <md-button ng-click="vm.insereLivro();" class="md-raised md-primary btnLivro">Inserir Livro</md-button>
                </fieldset>
                <fieldset class="ordenacao">
                    <legend>Ordenar Livros</legend>
                    <div class="InsertOrders">
                        <div class="selectOrdenacao">
                            <div class="atributos">
                                <label>Atributos</label>
                                <md-select ng-model="vm.atributoSelecionado">
                                    <md-optgroup label="Atributos">
                                        <md-option ng-value="key" ng-repeat="(key,val) in vm.attributes">{{val}}</md-option>
                                    </md-optgroup>
                                </md-select>
                            </div>

                            <div>
                                <label>Ordenação</label>
                                <md-select ng-model="vm.ordemSelecionada">
                                    <md-optgroup label="Ordem">
                                        <md-option ng-value="key" ng-repeat="(key,val) in vm.orders">{{val}}</md-option>
                                    </md-optgroup>
                                </md-select>
                                <md-button ng-click="vm.insereOrdem();" class="md-raised md-primary btnOrdem">Inserir Ordem</md-button>
                            </div>
                        </div>
                        <fieldset class="ordenacaoLista">
                            <legend>Ordem</legend>
                            <div ng-repeat="item in vm.ordensInterface"><md-button ng-click="vm.removeOrdem($index)" class="md-raised md-warn btnOrdemSelecionada">{{item.Attribute}} - {{item.Order}}</md-button></div>
                        </fieldset>
                    </div>
                </fieldset>

            </div>
            <md-button ng-click="vm.enviaOrdenacao();" class="md-raised md-primary btnEnviaOrdenacao">Enviar para Serviço de Ordenação</md-button>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            <a href="#">
                                Titulo <span ng-show="orderByField == 'firstName'"><span ng-show="!reverseSort">^</span><span ng-show="reverseSort">v</span></span>
                            </a>
                        </th>
                        <th>
                            <a href="#" >
                                Autor<span ng-show="orderByField == 'lastName'"><span ng-show="!reverseSort">^</span><span ng-show="reverseSort">v</span></span>
                            </a>
                        </th>
                        <th>
                            <a href="#">
                                Ano <span ng-show="orderByField == 'age'"><span ng-show="!reverseSort">^</span><span ng-show="reverseSort">v</span></span>
                            </a>
                        </th>
                        <th>

                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr ng-repeat="emp in vm.books">
                        <td>{{emp.Title}}</td>
                        <td>{{emp.AuthorName}}</td>
                        <td>{{emp.EditionYear}}</td>
                        <td><md-button ng-click="vm.remove($index)" class="md-raised md-primary btnRemover">Remover</md-button></td>
                    </tr>
                </tbody>
            </table>


        </div>
    </section>
</div>

ServicoOrdenacaoFGV.MVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ServicoOrdenacaoFGV.MVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ServicoOrdenacaoFGV.MVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">

</div>

ServicoOrdenacaoFGV.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Projeto FGV - CSO </title>
        @Scripts.Render("~/bundles/AngularJs")
        @Scripts.Render("~/bundles/AngularModules")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
 
        @Styles.Render("~/Content/css")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Projeto FGV", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("CSO", "Index", "Book")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Projeto FGV (CSO) - Desenvolvido por Marcelo Rodrigues.</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>